export const CATEGORIES_ACTION_TYPE = {
    GET_CATEGORIES_AND_DOCUMENTS: "categories/GET_CATEGORIES_AND_DOCUMENTS",
    FETCH_CATEGORIES_START: "categories/FETCH_CATEGORIES_START",
    FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
    FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
    FETCH_CATEGORIES: "categories/FETCH_CATEGORIES",
};
